# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "demo-application"
client_id = "e63f32fe52c417060d2b824615725df0"
application_url = "https://manually-genuine-genome-extended.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://manually-genuine-genome-extended.trycloudflare.com/auth/callback",
  "https://manually-genuine-genome-extended.trycloudflare.com/auth/shopify/callback",
  "https://manually-genuine-genome-extended.trycloudflare.com/api/auth/callback",
  "https://manually-genuine-genome-extended.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-e02e3c7d.myshopify.com"
